package dispatch

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/AgentGuardHQ/octi-pulpo/internal/learner"
)

const (
	defaultCataModel    = "deepseek-chat"
	cataTimeout         = 10 * time.Minute
	defaultCataBinary   = "cata"
	defaultCataProvider = "deepseek"
)

// CataAdapter dispatches tasks to the Cata governed CLI agent.
// Cata runs in an isolated git worktree, implements the task,
// commits, pushes a branch, and opens a PR.
type CataAdapter struct {
	binary    string // path to cata binary
	model     string
	provider  string
	workspace string // root workspace path
	learner   *learner.Learner
}

// NewCataAdapter creates a CataAdapter. Zero-value strings fall back to
// defaults: binary="cata", model="deepseek-chat", provider="deepseek",
// workspace="$HOME/agentguard-workspace".
func NewCataAdapter(binary, model, provider, workspace string) *CataAdapter {
	if binary == "" {
		binary = defaultCataBinary
	}
	if model == "" {
		model = defaultCataModel
	}
	if provider == "" {
		provider = defaultCataProvider
	}
	if workspace == "" {
		workspace = filepath.Join(os.Getenv("HOME"), "agentguard-workspace")
	}
	return &CataAdapter{
		binary:    binary,
		model:     model,
		provider:  provider,
		workspace: workspace,
	}
}

// Name returns the adapter identifier.
func (a *CataAdapter) Name() string { return "cata" }

// SetLearner enables automatic episodic memory storage for task outcomes.
func (a *CataAdapter) SetLearner(l *learner.Learner) { a.learner = l }

// CanAccept returns true for code-gen, bugfix, config, and evolve task types
// when DEEPSEEK_API_KEY is available in the environment.
func (a *CataAdapter) CanAccept(task *Task) bool {
	if os.Getenv("DEEPSEEK_API_KEY") == "" {
		return false
	}
	switch task.Type {
	case "code-gen", "bugfix", "config", "evolve", "prompt_config", "tool_addition", "config_change":
		return true
	default:
		return false
	}
}

// Dispatch runs Cata in an isolated git worktree to implement the task.
// On success the branch is pushed and a PR is opened. The worktree is removed
// on return regardless of outcome.
func (a *CataAdapter) Dispatch(ctx context.Context, task *Task) (*AdapterResult, error) {
	ctx, cancel := context.WithTimeout(ctx, cataTimeout)
	defer cancel()

	result := &AdapterResult{
		TaskID:  task.ID,
		Adapter: a.Name(),
	}

	// Resolve local repo path.
	repoPath := a.workspace
	if task.Repo != "" {
		repoName := filepath.Base(task.Repo)
		repoPath = filepath.Join(a.workspace, repoName)
	}

	// Create a git worktree for isolation so changes don't pollute the
	// main working tree.
	branchName := fmt.Sprintf("cata/%s", sanitizeBranch(task.ID))
	worktreePath := filepath.Join(a.workspace, ".worktrees", branchName)

	defaultBranch := detectDefaultBranch(repoPath)
	wtCmd := exec.CommandContext(ctx, "git", "worktree", "add", worktreePath, "-b", branchName, "origin/"+defaultBranch)
	wtCmd.Dir = repoPath
	if wtOut, wtErr := wtCmd.CombinedOutput(); wtErr != nil {
		result.Status = "failed"
		result.Error = fmt.Sprintf("worktree create failed: %s: %s", wtErr, string(wtOut))
		return result, nil
	}
	defer cleanupWorktree(repoPath, worktreePath, branchName)

	// Optionally prepend recalled prior experience to the prompt.
	prompt := task.Prompt
	if a.learner != nil {
		taskInfo := &learner.TaskInfo{
			Type: task.Type, Repo: task.Repo, Prompt: task.Prompt, Priority: task.Priority,
		}
		if prior := a.learner.RecallSimilar(ctx, taskInfo); prior != "" {
			prompt = prior + "\n\n" + prompt
		}
	}

	// Append PR creation instructions so Cata pushes and opens a PR.
	prompt += fmt.Sprintf(
		"\n\nAfter implementing, commit your changes and run:\n"+
			"git add -A && git commit -m 'feat: %s' && git push -u origin %s\n"+
			"Then open a PR: gh pr create --repo %s --title '%s' --body 'Auto-generated by Cata via /evolve dispatch\n\nTask: %s'",
		task.ID, branchName, task.Repo, truncate(task.Prompt, 60), task.ID,
	)

	args := []string{
		"run",
		"--provider", a.provider,
		"--model", a.model,
		"--max-turns", "100",
		"--timeout", fmt.Sprintf("%d", int(cataTimeout.Milliseconds())),
		prompt,
	}

	cmd := exec.CommandContext(ctx, a.binary, args...)
	cmd.Dir = worktreePath

	env := os.Environ()
	if key := os.Getenv("DEEPSEEK_API_KEY"); key != "" {
		env = append(env, fmt.Sprintf("DEEPSEEK_API_KEY=%s", key))
	}
	cmd.Env = env

	out, err := cmd.CombinedOutput()
	result.Output = string(out)

	if err != nil {
		result.Status = "failed"
		result.Error = fmt.Sprintf("cata exited: %v", err)
	} else {
		result.Status = "completed"
	}

	// Record outcome in episodic memory for future recall.
	if a.learner != nil {
		taskInfo := &learner.TaskInfo{
			Type: task.Type, Repo: task.Repo, Prompt: task.Prompt, Priority: task.Priority,
		}
		outcomeInfo := &learner.OutcomeInfo{
			Status:    result.Status,
			Adapter:   result.Adapter,
			TokensIn:  result.TokensIn,
			TokensOut: result.TokensOut,
			CostCents: result.CostCents,
			Output:    truncate(result.Output, 2000),
			Error:     result.Error,
		}
		_ = a.learner.RecordOutcome(ctx, taskInfo, outcomeInfo)
	}

	return result, nil
}

// sanitizeBranch converts a task ID to a valid git branch-name segment.
func sanitizeBranch(id string) string {
	r := strings.NewReplacer(" ", "-", "/", "-", ":", "-", ".", "-")
	return r.Replace(strings.ToLower(id))
}

// detectDefaultBranch checks whether the repo uses "main" or "master" as its
// default remote branch.
func detectDefaultBranch(repoPath string) string {
	cmd := exec.Command("git", "rev-parse", "--verify", "origin/main")
	cmd.Dir = repoPath
	if err := cmd.Run(); err == nil {
		return "main"
	}
	return "master"
}

// cleanupWorktree removes the worktree and local branch (best-effort).
func cleanupWorktree(repoPath, worktreePath, branchName string) {
	exec.Command("git", "worktree", "remove", "--force", worktreePath).Run()            //nolint:errcheck
	exec.Command("git", "-C", repoPath, "branch", "-D", branchName).Run()              //nolint:errcheck
}

// truncate is defined in leaderboard.go (shared within the dispatch package).
