package dispatch

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"time"
)

const (
	copilotCLIBinary  = "copilot"
	copilotCLITimeout = 30 * time.Minute
)

// CopilotCLIAdapter dispatches tasks to the GitHub Copilot CLI agent via
// `copilot -p`. Each task runs in an isolated git worktree.
type CopilotCLIAdapter struct {
	binary      string // path to copilot binary
	workspace   string // root workspace path
	modelRouter *ModelRouter
}

// NewCopilotCLIAdapter creates a CopilotCLIAdapter. Zero-value strings fall
// back to defaults: binary="copilot", workspace="$HOME/workspace".
func NewCopilotCLIAdapter(binary, workspace string) *CopilotCLIAdapter {
	if binary == "" {
		binary = copilotCLIBinary
	}
	if workspace == "" {
		workspace = filepath.Join(os.Getenv("HOME"), "workspace")
	}
	return &CopilotCLIAdapter{
		binary:      binary,
		workspace:   workspace,
		modelRouter: NewModelRouter(),
	}
}

// Name returns the adapter identifier.
func (a *CopilotCLIAdapter) Name() string { return "copilot-cli" }

// CanAccept returns true for task types that the Copilot CLI handles well.
func (a *CopilotCLIAdapter) CanAccept(task *Task) bool {
	switch task.Type {
	case "code-gen", "bugfix", "qa", "plan", "groom", "validate", "pr-review":
		return true
	default:
		return false
	}
}

// maxTurnsForType returns the --max-autopilot-continues value for a task type.
func maxTurnsForType(taskType string) int {
	switch taskType {
	case "groom":
		return 30
	case "plan":
		return 20
	case "validate", "qa", "pr-review":
		return 30
	case "code-gen", "bugfix":
		return 80
	default:
		return 30
	}
}

// buildArgs constructs the copilot CLI argument list for a task.
// repoPath is the worktree directory (used to locate mcp-swarm.json).
func (a *CopilotCLIAdapter) buildArgs(task *Task, repoPath string) []string {
	model := a.modelRouter.CopilotModel(task.Context)
	maxTurns := maxTurnsForType(task.Type)

	args := []string{
		"-p", task.Prompt,
		"--model", model,
		"--yolo",
		"--no-ask-user",
		"--silent",
		"--output-format", "json",
		"--max-autopilot-continues", fmt.Sprintf("%d", maxTurns),
	}

	// Attach MCP swarm config when present.
	mcpPath := filepath.Join(repoPath, "mcp-swarm.json")
	if _, err := os.Stat(mcpPath); err == nil {
		args = append(args, "--additional-mcp-config", "@"+mcpPath)
	}

	return args
}

// Dispatch runs Copilot CLI in an isolated git worktree to implement the task.
// The worktree is removed on return regardless of outcome.
func (a *CopilotCLIAdapter) Dispatch(ctx context.Context, task *Task) (*AdapterResult, error) {
	ctx, cancel := context.WithTimeout(ctx, copilotCLITimeout)
	defer cancel()

	result := &AdapterResult{
		TaskID:  task.ID,
		Adapter: a.Name(),
	}

	// Resolve local repo path.
	repoPath := a.workspace
	if task.Repo != "" {
		repoName := filepath.Base(task.Repo)
		repoPath = filepath.Join(a.workspace, repoName)
	}

	// Create an isolated git worktree.
	branchName := fmt.Sprintf("copilot/%s", sanitizeBranch(task.ID))
	worktreePath := filepath.Join(a.workspace, ".worktrees", branchName)

	defaultBranch := detectDefaultBranch(repoPath)
	wtCmd := exec.CommandContext(ctx, "git", "worktree", "add", worktreePath, "-b", branchName, "origin/"+defaultBranch)
	wtCmd.Dir = repoPath
	if wtOut, wtErr := wtCmd.CombinedOutput(); wtErr != nil {
		result.Status = "failed"
		result.Error = fmt.Sprintf("worktree create failed: %s: %s", wtErr, string(wtOut))
		return result, nil
	}
	defer cleanupWorktree(repoPath, worktreePath, branchName)

	args := a.buildArgs(task, worktreePath)
	cmd := exec.CommandContext(ctx, a.binary, args...)
	cmd.Dir = worktreePath
	cmd.Env = os.Environ()

	out, err := cmd.CombinedOutput()
	result.Output = string(out)

	if err != nil {
		result.Status = "failed"
		result.Error = fmt.Sprintf("copilot exited: %v", err)
	} else {
		result.Status = "completed"
	}

	// Push branch and open PR if Copilot produced commits.
	//
	// Honest-dispatch contract (refs: chitinhq/octi#242, chitinhq/octi#245,
	// workspace#408): Status="completed" must mean the agent's work reached
	// an observable surface (PR on origin). If `git push` or `gh pr create`
	// fails, revert Status to "failed" so the outer dispatcher in
	// dispatcher.go:264 maps it to Action="failed" instead of silently
	// claiming Action="dispatched" on a branch the remote never saw — the
	// worktree is about to be torn down by `cleanupWorktree`, so any such
	// claim is a silent loss.
	if result.Status == "completed" {
		if hasNewCommits(worktreePath, "origin/"+defaultBranch) {
			pushCmd := exec.CommandContext(ctx, "git", "push", "-u", "origin", branchName)
			pushCmd.Dir = worktreePath
			if pushOut, pushErr := pushCmd.CombinedOutput(); pushErr != nil {
				result.Status = "failed"
				result.Error = fmt.Sprintf("push failed: %s: %s", pushErr, string(pushOut))
			} else {
				prTitle := truncate(task.Prompt, 60)
				prBody := fmt.Sprintf("Auto-generated by Copilot CLI via Octi Pulpo dispatch\n\nTask: %s\nAdapter: %s\nType: %s", task.ID, a.Name(), task.Type)
				prCmd := exec.CommandContext(ctx, "gh", "pr", "create",
					"--repo", task.Repo,
					"--head", branchName,
					"--title", prTitle,
					"--body", prBody,
				)
				prCmd.Dir = worktreePath
				if prOut, prErr := prCmd.CombinedOutput(); prErr != nil {
					result.Status = "failed"
					result.Error = fmt.Sprintf("pr create failed: %s: %s", prErr, string(prOut))
				} else {
					result.Output = string(prOut)
				}
			}
		}
	}

	return result, nil
}
